[project]
name = "deep-g2p"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.1",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
    "typed-argument-parser>=1.10.1",
]
