name: Push to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Prepare and push to HF
        run: |
          # Prepare space
          mkdir phonemize-in-hebrew
          cd phonemize-in-hebrew
          cp ../examples/editor.py app.py

          # Editor deps
          echo "gradio>=5.25.2" >> requirements.txt            
          # Mishkal deps
          echo "num2words" >> requirements.txt            
          echo "colorlog" >> requirements.txt            
          echo "regex" >> requirements.txt
          # Phonikud deps
          echo "tokenizers" >> requirements.txt
          echo "onnxruntime" >> requirements.txt
          # Copy files
          cp ../.github/workflows/hf_readme.md README.md
          cp -rf ../mishkal .
          cp -rf ../phonikud_onnx/src/phonikud_onnx .

          # Setup phonikud model
          wget https://huggingface.co/thewh1teagle/phonikud/resolve/main/phonikud-1.0.int8.onnx
          git lfs install
          git lfs untrack "*.onnx"
          git rm --cached phonikud-1.0.int8.onnx
          rm -rf .git/lfs/objects
          git lfs track "*.onnx"

          # Initialize git and force push
          git config --global user.email "thewh1teagle"
          git config --global user.name "thewh1teagle"
          git init
          git branch -m master main
          git add .
          git commit -m "latest"
          git remote add space https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME
          git push --force space main

        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: "thewh1teagle"
          SPACE_NAME: "phonemize-in-hebrew"
